bugType:  DriverIssue

description:
	
	File test_move.py was broken because of the argument messages
	
	When we try to run "$ ./test_move.py" roslaunch server replies: 
	TypeError: Invalid number of arguments, args should be ....
	
bugFix:

	repository: https://github.com/ros-industrial/universal_robot.git
  
	pr: 26
  
	issue: 24
  
	branch: hydro-devel

	hash: 300e395d241d910ddc3cde0a8a6485ce0d1cfa28
		
  fix-in: 
	
	 ur_driver/src/ur_driver/driver.py 


